"use client";
import Link from "next/link";
import {useState} from "react";
import {LayoutDashboard, Package, FileText, MessageSquare, BarChart3, ExternalLink, Search, Plus, Settings} from "lucide-react";
import s from "./admin-workspace.module.css";

type Entry = {slug:string;title:string;status:string;category:string};
type Inquiry = {id:string;createdAt:string;source:"quote-form"|"chat-contact";name:string;email:string;company:string;market:string;machine:string;quantity:string;timeline:string;message:string;pageUrl:string;pageTitle:string;product:string;previousPage:string;entryPage:string;referrer:string};
const navigation = [
  ["overview","工作台",LayoutDashboard],["products","产品管理",Package],["news","文章与新闻",FileText],
  ["inbox","留言与聊天",MessageSquare],["analytics","访问分析",BarChart3],["settings","连接设置",Settings]
] as const;
export function AdminWorkspace({content,section,inquiries=[]}:{content:{products:Entry[];news:Entry[]};section:string;inquiries?:Inquiry[]}){
  const [search,setSearch] = useState("");
  const [status,setStatus] = useState("all");
  const umamiShareUrl = process.env.NEXT_PUBLIC_UMAMI_SHARE_URL || "https://stats.boholvending.com/share/TDZJE9DwE8PFyJe4";
  const umamiScriptUrl = process.env.NEXT_PUBLIC_UMAMI_SCRIPT_URL || "https://stats.boholvending.com/script.js";
  const umamiWebsiteId = process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID || "67526bd7-f75d-45f3-b748-86d84ac8ab32";
  const title = navigation.find(n=>n[0]===section)?.[1] || "工作台";
  const collection = section === "news" ? "news" : "products";
  const rows = content[collection].filter(x=>x.title.toLowerCase().includes(search.toLowerCase()) && (status==="all"||x.status===status));
  return <div className={s.shell}><aside className={s.sidebar}><Link className={s.brand} href="/admin">BOHOL <span>网站管理</span></Link><nav aria-label="后台导航">{navigation.map(([key,label,Icon])=><Link key={key} href={key==="overview"?"/admin":`/admin/${key}`} aria-current={section===key?"page":undefined}><Icon size={19}/>{label}</Link>)}</nav><a className={s.website} href="/" target="_blank" rel="noreferrer"><ExternalLink size={17}/>查看英文网站</a></aside><main className={s.main}><header className={s.top}><span>网站管理 / {title}</span><form method="post" action="/api/admin/logout"><button type="submit">退出登录</button></form></header><div className={s.content}><div className={s.heading}><div><h1>{title}</h1><p>管理真实内容，查看发布状态和服务连接。</p></div>{["products","news","overview"].includes(section)&&<Link className={s.primary} href={`/keystatic/collection/${collection}/create`}><Plus size={17}/>新建{collection==="news"?"文章":"产品"}</Link>}</div>
  {section==="overview"?<><div className={s.summary}><Link href="/admin/products"><span>产品内容</span><strong>{content.products.length}</strong><small>来自内容目录</small></Link><Link href="/admin/news"><span>文章内容</span><strong>{content.news.length}</strong><small>后台创建的文章</small></Link><Link href="/admin/products"><span>产品草稿</span><strong>{content.products.filter(x=>x.status==="draft").length}</strong><small>未对外发布</small></Link></div><section className={s.panel}><h2>访问数据</h2><p>Umami 已接入主站。下面直接显示完整报表和国家来源。</p><div className={s.actions}><Link href="/admin/analytics">打开访问分析页 →</Link></div><div className={s.countryFrame}><iframe title="BOHOL complete analytics" src={umamiShareUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><div className={s.countryFrame}><iframe title="BOHOL traffic countries" src={`${umamiShareUrl}?view=country`} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><p>新系统只统计接入后的访问，历史 GA 数据不会自动导入。</p></section><section className={s.panel}><h2>开始管理</h2><p>产品名称、正文与 SEO 文案请填写英文。保存后的内容需要网站重新部署，才能更新线上页面。</p><div className={s.actions}><Link href="/admin/products">管理产品 →</Link><Link href="/admin/news">管理文章 →</Link></div></section><section className={s.panel}><h2>接入进度</h2><p>留言：目前通过邮件表单发送，尚无后台收件箱。</p><p>聊天：目前为预设自动回复，尚无客服消息存储。</p><p>Umami：统计代码、HTTPS、分享报表和工作台内嵌报表已接入。</p></section></>:
  ["products","news"].includes(section)?<section className={s.panel}><div className={s.filters}><label><Search size={17}/><input aria-label="搜索内容" placeholder="搜索标题…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="发布状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="published">已发布</option><option value="draft">草稿</option></select><span>{rows.length} 条内容</span></div><div className={s.tableWrap}><table><thead><tr><th>内容标题</th><th>{collection==="news"?"发布日期":"分类"}</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.slug}><td><b>{row.title}</b><small>{row.slug}</small></td><td>{row.category}</td><td><span className={row.status==="published"?s.published:s.draft}>{row.status==="published"?"已发布":"草稿"}</span></td><td><Link href={`/keystatic/collection/${collection}/item/${row.slug}`}>编辑</Link>{row.status==="published"&&<a href={`/${collection==="news"?"insights":"vending-machines"}/${row.slug}`} target="_blank" rel="noreferrer">查看网站</a>}</td></tr>)}</tbody></table></div>{!rows.length&&<div className={s.empty}><h2>{search?"没有匹配内容":"还没有内容"}</h2><p>{collection==="news"?"网站原有研究文章仍来自前台内容文件，尚未迁入编辑器。新文章可通过右上角新建。":"试试其他关键词或新建产品。"}</p></div>}</section>:
  section==="analytics"?<><section className={s.panel}><h2>Umami 访问分析</h2><p>当前改用 Umami 统计。它会在浏览器空闲时加载，主要记录访问页面、来源、设备和关键按钮事件。</p>{umamiScriptUrl&&umamiWebsiteId?<p>网站统计代码已配置：{umamiWebsiteId}</p>:<p>统计代码尚未配置。上线后需要填入 Umami Script URL 和 Website ID。</p>}{umamiShareUrl?<a className={s.primary} href={umamiShareUrl} target="_blank" rel="noreferrer">打开完整报表 <ExternalLink size={17}/></a>:<p>后台嵌入面板尚未配置。安装 Umami 后，把 Share URL 填入环境变量即可在下方直接显示。</p>}</section>{umamiShareUrl?<section className={s.analyticsFrame} aria-label="Umami 访问分析报表"><iframe title="BOHOL Umami analytics" src={umamiShareUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section>:<section className={s.panel}><h2>准备追踪的事件</h2><p>报价表单提交、在线聊天打开、快速问题、留言、Email、WhatsApp、WeChat、Facebook、YouTube 点击。</p></section>}</>:
  section==="inbox"?<section className={s.panel}><h2>前台留言收件箱</h2><p>这里显示前台询盘表单和右下角聊天留言提交的新消息。历史网页聊天没有存储，不能补回。</p>{inquiries.length?<div className={s.inquiryList}>{inquiries.map(item=><article className={s.inquiryCard} key={item.id}><header><div><strong>{item.name}</strong><span>{item.source==="chat-contact"?"聊天留言":"询盘表单"}</span></div><time>{new Date(item.createdAt).toLocaleString("zh-CN",{hour12:false})}</time></header><p>{item.message}</p><dl><div><dt>邮箱</dt><dd><a href={`mailto:${item.email}`}>{item.email}</a></dd></div>{item.company&&<div><dt>公司</dt><dd>{item.company}</dd></div>}{item.market&&<div><dt>市场</dt><dd>{item.market}</dd></div>}{item.machine&&<div><dt>产品</dt><dd>{item.machine}</dd></div>}{item.quantity&&<div><dt>数量</dt><dd>{item.quantity}</dd></div>}{item.timeline&&<div><dt>时间</dt><dd>{item.timeline}</dd></div>}{item.pageUrl&&<div><dt>来源页面</dt><dd><a href={item.pageUrl} target="_blank" rel="noreferrer">{item.pageTitle || item.pageUrl}</a></dd></div>}</dl></article>)}</div>:<div className={s.empty}><h2>还没有新留言</h2><p>前台询盘表单和聊天留言已经接入；客户提交后会出现在这里。</p></div>}</section>:
  <section className={s.panel}><h2>当前数据来源</h2><p>产品 / 文章：Keystatic 本地内容目录。</p><p>保存：写入当前运行环境；本地编辑后需提交部署。</p><p>Sanity：产品读取代码已有接入分支；请先确认是否启用，避免两个内容源互相覆盖。</p><p>留言 / 客服：尚未配置身份验证与消息数据库。</p></section>}
  </div></main></div>;
}
