"use client";
import { useEffect, useState } from "react";
import { Mail, MessageCircle, Facebook, Youtube, X, Send } from "lucide-react";
import s from "./contact-float.module.css";
function WeChatIcon(){return <svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14.5 6.2C14 4.2 11.8 3 9.2 3 5.8 3 3 5 3 7.7c0 1.5.8 2.8 2.2 3.7L4.6 13l2.3-1.1c.7.2 1.5.3 2.3.3"/><path d="M14 9c3.3 0 6 1.8 6 4.3 0 1.3-.7 2.4-1.9 3.2l.4 1.5-2-1c-.8.3-1.6.4-2.5.4-3.3 0-6-1.8-6-4.1S10.7 9 14 9Z"/><circle cx="11" cy="7.5" r=".7" fill="currentColor" stroke="none"/><circle cx="16.8" cy="12.8" r=".7" fill="currentColor" stroke="none"/></svg>}
const links=[["Email","mailto:sales@boholvending.com",Mail,"#66b447"],["WhatsApp","https://wa.me/8619128839757",MessageCircle,"#43c653"],["WeChat","#wechat",WeChatIcon,"#18bd0b"],["Facebook","https://www.facebook.com/",Facebook,"#1877f2"],["YouTube","https://www.youtube.com/",Youtube,"#f00"]] as const;
function smartReply(text:string){const t=text.toLowerCase();if(/vape|cigarette|烟/.test(t))return "We can help with vape vending formats. Tell us your market and local age-verification requirements.";if(/drink|beverage|冷饮|饮料/.test(t))return "For cold drinks, we’ll review can or bottle size, temperature range and expected daily volume.";if(/price|quote|cost|报价|价格/.test(t))return "We prepare a quote from product type, quantity, destination and customization. Leave your email for a precise offer.";if(/custom|oem|odm|brand|定制/.test(t))return "Yes. BOHOL can discuss cabinet finish, channels, interface, payment and branding options.";if(/pay|payment|card|支付/.test(t))return "Payment terminals can be configured for card, mobile wallet and QR methods available in your market.";if(/lead|delivery|time|交期|多久/.test(t))return "Timing depends on configuration and quantity. Share your target launch date and we’ll map the next steps.";if(/whatsapp|phone|联系/.test(t))return "You can reach BOHOL on WhatsApp at +86 19128839757.";return "I can help with product choice, pricing, customization, payment or delivery. Which one should we start with?"}
export function ContactFloat(){const [ready,setReady]=useState(false);const [open,setOpen]=useState(false);const [form,setForm]=useState(false);const [sent,setSent]=useState(false);const [reply,setReply]=useState("");useEffect(()=>{const timer=window.setTimeout(()=>setReady(true),1800);return()=>window.clearTimeout(timer)},[]);const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=`Name: ${d.get("name")}\nEmail: ${d.get("email")}\nMessage: ${d.get("message")}`;setSent(true);window.location.href=`mailto:sales@boholvending.com?subject=Offline%20chat%20message&body=${encodeURIComponent(body)}`};const chat=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setReply(smartReply(String(d.get("chat"))));e.currentTarget.reset()};if(!ready)return null;return <div className={s.wrap}>{open&&<div className={s.panel} role="dialog" aria-label="Contact BOHOL"><div className={s.panelHead}><div><strong>BOHOL team</strong><small className={s.status}><i className={s.online}/> Online now</small></div><button onClick={()=>setOpen(false)} aria-label="Close contact panel"><X size={18}/></button></div>{sent?<p className={s.thanks}>Thanks. Your message is ready to send to our team.</p>:form?<><div className={s.chatBubble}>We’re away right now. Leave your details and we’ll get back to you.</div><form onSubmit={submit} className={s.form}><input name="name" required placeholder="Your name"/><input name="email" type="email" required placeholder="Business email"/><textarea name="message" required placeholder="How can we help?" rows={3}/><button className={s.panelCta} type="submit">Send message <Send size={16}/></button></form></>:<><div className={s.chatBubble}>Hello! I can help with products, pricing, customization and delivery.</div>{reply&&<div className={s.chatReply}>{reply}</div>}<form onSubmit={chat} className={s.chatForm}><input name="chat" required placeholder="Type a message…"/><button aria-label="Send chat message"><Send size={17}/></button></form><button className={s.leave} onClick={()=>setForm(true)}>Leave contact details if we miss you</button></>}</div>}<div className={s.links}>{links.map(([label,href,Icon,color])=><a key={label} href={href} target={href.startsWith("http")?"_blank":undefined} rel="noreferrer" aria-label={label} title={label} style={{backgroundColor:color}}><Icon size={21}/></a>)}</div><button className={s.launch} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?"Close contact panel":"Open contact panel"}>{open?<X size={25}/>:<MessageCircle size={25}/>}</button></div>}

