"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ExternalLink, LoaderCircle, Upload } from "lucide-react";
import s from "./admin-workspace.module.css";
type Status={configured:boolean;connected:boolean}; type Row={keys:string[];clicks:number;impressions:number;ctr:number;position:number};
export function SearchConsolePanel(){
  const [status,setStatus]=useState<Status|null>(null),[days,setDays]=useState(28),[dimension,setDimension]=useState("query"),[data,setData]=useState<{range:{startDate:string;endDate:string};totals:Row;rows:Row[]}|null>(null),[error,setError]=useState("");
  const loadStatus=()=>fetch("/api/admin/google-search-console/status").then(r=>r.json()).then(setStatus).catch(()=>setError("无法读取连接状态。"));
  useEffect(()=>{void loadStatus()},[]); useEffect(()=>{if(!status?.connected)return;fetch(`/api/admin/google-search-console/data?days=${days}&dimension=${dimension}`).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error);setData(v)}).catch(()=>setError("无法读取 Search Console 数据，请重新连接或稍后重试。"))},[status?.connected,days,dimension]);
  async function upload(form:FormData){setError("");const r=await fetch("/api/admin/google-search-console/configure",{method:"POST",body:form});if(r.ok)loadStatus();else setError("JSON 无效。请确认使用刚创建的 Web OAuth 客户端文件和正确回调地址。");}
  if(!status)return <section className={s.panel}><p><LoaderCircle size={18}/> 正在检查 Google 连接…</p></section>;
  if(!status.configured)return <section className={s.panel}><h2>连接 Google Search Console</h2><p>上传刚下载的 OAuth JSON。文件只保存到服务器私有目录，不会进入公开网站或 GitHub。</p><form className={s.gscUpload} action={upload}><input type="file" name="credentials" accept="application/json,.json" required/><button type="submit"><Upload size={16}/>上传并安全保存</button></form>{error&&<p role="alert">{error}</p>}</section>;
  if(!status.connected)return <section className={s.panel}><h2>授权 Search Console 数据</h2><p>OAuth 配置已安全保存。点击后使用拥有 boholvending.com Search Console 权限的 Google 账号授权只读访问。</p><Link className={s.primary} href="/api/admin/google-search-console/connect">连接 Google 账号 <ExternalLink size={16}/></Link>{error&&<p role="alert">{error}</p>}</section>;
  const t=data?.totals||{clicks:0,impressions:0,ctr:0,position:0};return <section className={s.panel}><div className={s.snapshotHead}><div><h2>Google Search Console 实时数据</h2><p>{data?`${data.range.startDate}–${data.range.endDate}`:"正在读取…"}</p></div><a className={s.primary} href="https://search.google.com/search-console?resource_id=sc-domain%3Aboholvending.com" target="_blank" rel="noreferrer">打开 Search Console <ExternalLink size={16}/></a></div><div className={s.gscControls}><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 天</option><option value="28">28 天</option><option value="90">3 个月</option></select><select value={dimension} onChange={e=>setDimension(e.target.value)}><option value="query">查询词</option><option value="page">网页</option><option value="country">国家/地区</option><option value="device">设备</option><option value="date">日期</option></select></div><div className={s.gscMetrics}><div><span>总点击</span><b>{t.clicks}</b></div><div><span>总曝光</span><b>{t.impressions}</b></div><div><span>平均点击率</span><b>{(t.ctr*100).toFixed(1)}%</b></div><div><span>平均排名</span><b>{t.position.toFixed(1)}</b></div></div>{error&&<p role="alert">{error}</p>}<div className={s.tableWrap}><table><thead><tr><th>{dimension}</th><th>点击</th><th>曝光</th><th>CTR</th><th>排名</th></tr></thead><tbody>{data?.rows.map((row,i)=><tr key={`${row.keys[0]}-${i}`}><td>{row.keys[0]}</td><td>{row.clicks}</td><td>{row.impressions}</td><td>{(row.ctr*100).toFixed(1)}%</td><td>{row.position.toFixed(1)}</td></tr>)}</tbody></table></div></section>;
}
