export const products=[
 {slug:"vape-vending-machine",name:"Vape Vending Machine",category:"Age-restricted retail",summary:"Configurable identity and age-verification integrations for compliant unattended retail.",image:"/images/hero/vape-machine.webp",features:["Age verification ready","Remote inventory","Modular payment terminal"]},
 {slug:"cold-drink-vending-machine",name:"Cold Drink Vending Machine",category:"Food & beverage",summary:"Energy-efficient refrigerated vending with flexible product channels and telemetry.",image:"/images/hero/cold-drink-machine.webp",features:["2-8°C cooling","Anti-fog display","Smart temperature alerts"]},
 {slug:"elevator-vending-machine",name:"Elevator Vending Machine",category:"Gentle delivery",summary:"Elevator delivery protects fragile, premium and irregular products from drops.",image:"/images/hero/elevator-machine.webp",features:["Multi-axis elevator","Large pickup bay","Flexible shelf geometry"]},
 {slug:"eyelash-vending-machine",name:"Eyelash Vending Machine",category:"Beauty retail",summary:"Premium beauty merchandising with an elegant, compact automated storefront.",image:"/images/hero/eyelash-machine.webp",features:["Illuminated display","Compact footprint","Custom brand finish"]},
 {slug:"card-vending-machine",name:"Card Vending Machine",category:"Collectibles retail",summary:"Smart vending for trading cards, blind boxes and compact collectible products.",image:"/images/hero/card-machine.webp",features:["Card-pack channels","Secure display cabinet","Touchscreen payment flow"]},
];
export const sections:Record<string,{eyebrow:string;title:string;intro:string;items:string[]}>= {
 solutions:{eyebrow:"SOLUTIONS",title:"Vending solutions for overseas retail locations.",intro:"Explore BOHOL hardware, software, payment and operation concepts for offices, hotels, apartments, gyms, hospitals, schools and public facilities.",items:["Smart retail operations","Payment & telemetry","Age verification","Global deployment support"]},
 "oem-odm":{eyebrow:"OEM & ODM",title:"Custom vending machines for global rollout.",intro:"From destination-market requirements to cabinet branding, product channel design, sample validation and mass production.",items:["Requirement discovery","Industrial design","Prototype & validation","Mass production"]},
 projects:{eyebrow:"PROJECTS & CASES",title:"Overseas application cases for smart vending.",intro:"Scenario-based vending case ideas for the United States, Canada, Europe, the UK, UAE, Singapore, Australia and global distributors.",items:["Office vending","Apartment lobby retail","Hotel and gym vending","Healthcare and campus vending"]},
 manufacturing:{eyebrow:"MANUFACTURING",title:"Precision you can scale.",intro:"Integrated engineering, metal fabrication, assembly and quality control under one roof.",items:["Incoming material inspection","CNC & sheet metal","Assembly & burn-in","Final quality assurance"]},
 insights:{eyebrow:"INSIGHTS",title:"Vending industry news & insights.",intro:"Industry research, payment technology and practical buying guidance for vending operators, distributors and brands. Original sources. Clear analysis.",items:["Choosing a vending platform","Understanding payment options","Designing for serviceability","Launch planning checklist"]},
 about:{eyebrow:"ABOUT BOHOL",title:"An engineering partner for global automated retail.",intro:"BOHOL combines manufacturing discipline with the curiosity to solve new retail challenges.",items:["Engineering-led","Built for export","Long-term support","Responsible manufacturing"]},
 contact:{eyebrow:"GET A QUOTE",title:"Tell us what you want to vend.",intro:"Share the product, market and rollout plan. Our engineering team will respond with the right starting point.",items:["Product & dimensions","Target market","Payment needs","Estimated quantity"]},
};
