name: Deploy BOHOL website

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy website
        run: sudo /var/www/bohol-vending/deploy/deploy.sh
